// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUkwU-d_4KoILBMgvC3TmWfLwf-jyxBk',
    appId: '1:417736739928:web:762ee8d2c6a16d85ea4e2d',
    messagingSenderId: '417736739928',
    projectId: 'family-tree-project-fabf2',
    authDomain: 'family-tree-project-fabf2.firebaseapp.com',
    storageBucket: 'family-tree-project-fabf2.firebasestorage.app',
    measurementId: 'G-373J34F7KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCqUDlR0e5x76oA2kG5bmwdVL7PtRNo8',
    appId: '1:417736739928:android:6fed9ef8ca86ec12ea4e2d',
    messagingSenderId: '417736739928',
    projectId: 'family-tree-project-fabf2',
    storageBucket: 'family-tree-project-fabf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARrRl8B6c4EfqozbgjU12sMDHxQfO7Jq0',
    appId: '1:417736739928:ios:70457a899f3d5098ea4e2d',
    messagingSenderId: '417736739928',
    projectId: 'family-tree-project-fabf2',
    storageBucket: 'family-tree-project-fabf2.firebasestorage.app',
    iosBundleId: 'com.example.familyTreeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARrRl8B6c4EfqozbgjU12sMDHxQfO7Jq0',
    appId: '1:417736739928:ios:70457a899f3d5098ea4e2d',
    messagingSenderId: '417736739928',
    projectId: 'family-tree-project-fabf2',
    storageBucket: 'family-tree-project-fabf2.firebasestorage.app',
    iosBundleId: 'com.example.familyTreeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhUkwU-d_4KoILBMgvC3TmWfLwf-jyxBk',
    appId: '1:417736739928:web:6da94f8290eab5d4ea4e2d',
    messagingSenderId: '417736739928',
    projectId: 'family-tree-project-fabf2',
    authDomain: 'family-tree-project-fabf2.firebaseapp.com',
    storageBucket: 'family-tree-project-fabf2.firebasestorage.app',
    measurementId: 'G-BNQXV7FL2P',
  );
}
